frase = 'Curso em Vídeo Python'
print('-='*15)
print('{:^30}'.format('Transformação'))
print('-='*15)
print(frase.replace('Python', 'Android'))
print(frase.upper())
print(frase.capitalize())
print(frase.title())
print(frase.lower())
print(frase.strip())
print('-='*15)
print('{:^30}'.format('Fatiamento'))
print('-='*15)
print(frase[9:12])
print(frase[:7])
print(frase[8::4])
print('-='*15)
print('{:^30}'.format('Análise'))
print('-='*15)
print(frase.count('d'))
print(frase.find('deo'))
print(len(frase))
print(frase.count('i', 0, 17))
print('Android' in frase)
print('-='*15)
print('{:^30}'.format('Divisão'))
print('-='*15)
print(frase.split())
div = frase.split()
print(div[2][3])
print('-='*15)
print('{:^30}'.format('Junção'))
print('-='*15)
print(' '.join(frase))
