n = int(input('\033[36mDigite um número:\033[m '))
a = (n-1)
s = (n+1)
print(f'\033[32m O número {n} tem o antecessor {a} e sucessor {s}\033[m')
#n=int(input('Digite um número: '))
#print('O número {} tem como antecessor {} e Sucessor {}'.format(n, (n-1), (n+1)))
